# Generated by Django 6.1 on 2026-09-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_name',
        ),
    ]
